### ISSUE TITLE
Production deployment behind nginx

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/CPD#1]
I wanted to point out that in order to deploy behind nginx there are some properties that are different from the `example.properties`:
  - `cpd.server.pub.host` is linked to `cpd.server.host`, but we have for the former `localhost` and our domain for the latter.
  - The same happens with `cpd.server.pub.port` and `cpd.server.port`. One thing is the project's port (`8901`) and other is the port of nginx.

If we are missunderstanding something please tell us. But this configuration is working for us.

**Comment by vcartelli** [comment]
The `.pub` properties must refer to the proxy domain and port.
This is an excerpt of a production.properties for an instance running behind an Apache2 reverse proxy:
```
  cpd.server.scheme=http
  cpd.server.host=localhost
  cpd.server.port=8901
  ! server.public
  cpd.server.pub.scheme=https
  cpd.server.pub.host=simpatico.business-engineering.it
  cpd.server.pub.port=443
```
