### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/CPD#4]
Hi,
We just pulled from the repo to update the version we have in our server. When running `deploy.sh` maven gives an error when compiling. The trace is here: https://pastebin.com/sqBrTDpW
Basically, there is some function error in `/microservice/ModelerServerVerticle.java:192`.
Could you please fix it or tell us how to fix it? Thanks.

**Comment by vcartelli** [comment]
It seems like your pom.xml is not updated...
