### ISSUE TITLE
run the docker version

### ISSUE THREAD

**Issue by mirkoperillo** [SIMPATICOProject/CPD#6]
Hi, 
I'm trying to run the docker version of the component. I have some problem
My steps:
1. create a local image from Dockerfile
`docker build -t cpd-sample .`
2. try to run a new container from image
`docker run cpd-sample`

The problem is that the container exits soon.
Reading the Dockerfile I don't find any instructions that should run the application.

I need some documentations about.

**Comment by gdimodica** [comment]
Instructions on how to deploy a dockerized version of the CPD have been reported in the README. The dockerization though is still being tested, so there is no guarantee that it works as expected. Tomorrow a stable release will appear
