### ISSUE TITLE
CPD behind nginx

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/CPD#8]
Could you add to the documentation that the project uses Websockets?
We have everything behind nginx and we had to add a few lines to the configuration in order to make it work. And it took a while to get why it wasn't working.
```
# Socket.IO Support
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

**Comment by vcartelli** [comment]
Done. Thank you
